language: node_js
node_js:
  - "8"

sudo: required

cache:
  yarn: true
  directories:
    - node_modules

git:
  depth: 10

branches:
  only:
  - develop

install:
  - yarn install

script:
  - yarn run build

after_success:
  - sudo apt-get install ssh sshpass -y
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - ssh-keyscan -H $TIMEWEB_HOST >> ~/.ssh/known_hosts
  - sshpass -p "$TIMEWEB_SSH_PASSWORD" scp -r ./public/* $TIMEWEB_SSH_LOGIN@$TIMEWEB_HOST:$TIMEWEB_DEVELOP_DIR