language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

git:
  depth: 10

branches:
  only:
  - develop

install:
  - yarn install

script:
  - yarn run build

after_success:
    "curl -T public/ --ftp-create-dirs -u $FTP_USER:$FTP_PASSWORD ftp://margaret.timeweb.ru/like-o-meter.ru/public_html/develop/"