language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - sshpass

cache:
  directories:
    - node_modules

git:
  depth: 10

branches:
  only:
  - master
  - develop

install:
  - npm install

script:
  - npm run build

after_success:
  - sudo apt-get update
  - sudo apt-get install ssh sshpass -y
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - ssh-keyscan -H $TIMEWEB_HOST >> ~/.ssh/known_hosts
  - '[[ $TRAVIS_BRANCH == "master" ]] && DIR="$TIMEWEB_PRODUCTION_DIR" || DIR="$TIMEWEB_DEVELOP_DIR"'
  - sshpass -p "$TIMEWEB_SSH_PASSWORD" scp -r ./public/* $TIMEWEB_SSH_LOGIN@$TIMEWEB_HOST:~/$DIR