export const VK_API_VERSION = 5.65;

export const API_URL_BACK = '';
export const CHECKING_AUTH = 'CHECKING_AUTH';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_STATE = 'FETCH_USERS_STATE';

export const FETCH_BILL = 'FETCH_BILL';
export const FETCH_BILL_STATE = 'FETCH_BILL_STATE';
export const BILL_STATUS_IN_PROGRESS = 0;
export const BILL_STATUS_DONE = 1;
export const BILL_STATUS_ERROR = 2;

export const FETCH_COMPANY = 'FETCH_COMPANY';
export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const FETCH_COMPANY_STATE = 'FETCH_COMPANY_STATE';

export const FETCH_COMPANY_CATEGORY = 'FETCH_COMPANY_CATEGORY';
export const FETCH_COMPANY_CATEGORIES = 'FETCH_COMPANY_CATEGORIES';
export const FETCH_COMPANY_CATEGORY_STATE = 'FETCH_COMPANY_CATEGORY_STATE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_STATE = 'FETCH_USER_STATE';

export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const FETCH_ALBUMS_STATE = 'FETCH_ALBUMS_STATE';

export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const FETCH_FRIENDS_STATE = 'FETCH_FRIENDS_STATE';